{"spider":"https://raw.kkgithub.com/asdjkl66/m/master/live.jar","wallpaper":"http://ceshi.xn--z7x900a.com/ppic/feimao.php", 
"lives":[{"name":"电视live","type":0,"playerType":1,"url":"./live.txt"},
{"name":"皇1","type":0,"url":"https://git.acwing.com/pxiptv/tv/-/raw/main/txt/1.txt"},
{"name":"皇2","type":0,"url":"https://git.acwing.com/pxiptv/tv/-/raw/main/txt/2.txt"},
{"name":"皇3","type":0,"url":"https://git.acwing.com/pxiptv/tv/-/raw/main/txt/3.txt"},
{"name":"皇4","type":0,"url":"https://git.acwing.com/pxiptv/tv/-/raw/main/txt/4.txt"},
{"name":"皇5","type":0,"url":"https://git.acwing.com/pxiptv/tv/-/raw/main/txt/5.txt"},
{"name":"皇6","type":0,"url":"https://notabug.org/zx/z/raw/main/b/国产传媒.txt"}],

"sites":[
{"key":"爱奇艺弹幕","name":"奇艺弹幕","type":3,"api":"https://cdn09022024.gitlink.org.cn/api/v1/repos/guot55/bhmax/raw/JS/drpy2.min.js","ext":"https://cdn09022024.gitlink.org.cn/api/v1/repos/guot55/bhmax/raw/JS/爱奇艺弹幕.js"},
{"key":"腾讯弹幕","name":"腾讯弹幕","type":3,"api":"https://cdn09022024.gitlink.org.cn/api/v1/repos/guot55/bhmax/raw/JS/drpy2.min.js","ext":"https://cdn09022024.gitlink.org.cn/api/v1/repos/guot55/bhmax/raw/JS/腾讯弹幕.js"},   
{"key":"优酷弹幕","name":"优酷弹幕","type":3,"api":"https://cdn09022024.gitlink.org.cn/api/v1/repos/guot55/bhmax/raw/JS/drpy2.min.js","ext":"https://cdn09022024.gitlink.org.cn/api/v1/repos/guot55/bhmax/raw/JS/优酷弹幕.js"},
{"key":"芒果弹幕","name":"芒果弹幕","type":3,"api":"https://cdn09022024.gitlink.org.cn/api/v1/repos/guot55/bhmax/raw/JS/drpy2.min.js","ext":"https://cdn09022024.gitlink.org.cn/api/v1/repos/guot55/bhmax/raw/JS/芒果弹幕.js"},
{"key":"js_星芽短剧","name":"星芽短剧","type":3,"api":"https://git.acwing.com/gggwang/gggwang/-/raw/main/LIBS/drpy2.min.js","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://git.acwing.com/gggwang/gggwang/-/raw/main/JS/星芽短剧.js"},

    //🔞成人视频
{"key":"葡萄","name":"🔞葡萄资源","type":1,"api":"https://caiji.putaozyw.net/inc/apijson_vod.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"采集","name":"☪采王密🔞","type":3,"api":"https://ghfast.top/https://raw.githubusercontent.com/n3rddd/N3RD/master/JN/dr_py/libs/drpy2.min.js","searchable":1, "quickSearch":1,"filterable":1,"order_num":1,"ext":"./合.js?type=url&params=./采集.json"},
{"key":"csp_xBPQ_tt-公子","name":"🔞黄色仓库","type":3,"api":"csp_xBPQ","jar":"https://git.acwing.com/66tv/669/-/raw/main/jar/xb.jar","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://git.acwing.com/66tv/669/-/raw/main/mov/json/黄色仓库xyz.json"},
{"key":"csp_xBPQ_ttyd-公子","name":"🔞天天综合","type":3,"api":"csp_xBPQ","jar":"https://git.acwing.com/66tv/669/-/raw/main/jar/xb.jar","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://git.acwing.com/66tv/669/-/raw/main/mov/json/天天综合.json"},


{"key":"8天","name":"🔞8天视频","type":1,"api":"https://8day.icu/api.php/provide/vod/at/json","searchable":1,"quickSearch":1,"filterable":1},

{"key":"drpyS_七度空间[密]","name":"🔞七度空间","type": 4,"api": "http://drpy.mxlgsl.cn/api/七度空间[密]","searchable": 1,"filterable": 1,"quickSearch": 0,"ext": ""},
{"key":"csp_XYBQ","name":"🔞比卡比卡","type":3,"api":"csp_XBPQ","jar":"https://py.nxog.eu.org/https://raw.githubusercontent.com/guot55/yg/main/jar/hl.jar","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://py.nxog.eu.org/https://raw.githubusercontent.com/guot55/yg/main/h/比卡比卡.json"},
{"key":"JKun","name":"🔞JKun资源","type":1,"api":"https://jkunzy.live/api.php/provide/vod","searchable": 1,"quickSearch":1,"filterable":0},
{"key":"丝袜","name":"🔞丝袜资源","type":1,"api":"https://www.siwazyw.tv/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"深林","name":"🔞深林资源","type":1,"api":"https://slapibf.com/api.php/provide/vod/at/json","searchable":1,"quickSearch":1,"filterable":1},
{"key":"湿园","name":"🔞湿园资源","type":1,"api":"https://xxavs.com/api.php/provide/vod/at/json","searchable":1,"quickSearch":1,"filterable":1},
{"key":"优异","name":"🔞优异资源","type":1,"api":"https://a.uezy.pw/api.php/provide/vod/at/json","searchable":1,"quickSearch":1,"filterable":1},
{"key":"色逼","name":"🔞色逼资源","type":1,"api":"https://a.uezy.pw/api.php/provide/vod/at/json","searchable":1,"quickSearch":1,"filterable":1},
{"key":"桃花","name":"🔞桃花资源","type":0,"api":"https://thzy4.me/api.php/provide/vod/at/xml","searchable":1,"quickSearch":1,"filterable":0},
{"key":"*91资源","name":"91麻豆🔞","type":1,"api":"http://www.9191md.me/api.php/provide/vod","searchable": 1,"quickSearch": 1},
   
{"key":"精东","name":"🔞精东资源","type":1,"api":"http://chujia.cc/api.php/provide/vod/from/m3u8/","searchable":1,"quickSearch":1,"filterable":1},


{"key":"laosebizy.com","name":"🔞色逼资源","type":1,"api":"https://apilsbzy1.com/api.php/provide/vod/?ac=list","searchable":1,"filterable":1},
{"key":"富二代-公子","name":"🔞富二代","type":0,"api":"http://f2dcj6.com/sapi?ac=list","searchable":1,"quickSearch":1,"filterable":0},
{"key":"奥斯卡资源网","name":"🔞奥斯卡","type":1,"api":"https://aosikazy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"乐播资源","name":"🔞乐播资源","type":1,"api": "https://lbapi9.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"155","name":"🔞155","type":0,"playerType":2,"api":"https://155api.com/api.php/provide/vod/at/xml","searchable":0,"quickSearch":0},
{"key":"api.11bat.com","name":"🔞11bat资源","type":0,"api":"http://api.11bat.com/api.php/provide/vod/at/xml","searchable":1,"recordable":0,"style": {"type":"rect","ratio": 1.33},"header":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","User-Agent":"Mozilla/5.0(WindowsNT10.0;Win64;x64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/117.0.0.0Safari/537.36"}},
{"key":"00色猫资源","name":"🔞色猫资源","type":1,"api": "https://api.maozyapi.com/inc/apijson_vod.php","playUrl":"https://api.maozyapi.com/m3u8/?url=","searchable":1,"quickSearch":1},
{"key":"didizy.com","name":"🔞滴滴资源","type":1,"api":"https://api.ddapi.cc/api.php/provide/vod/?ac=list","searchable":1,"filterable":1},
{"key":"*森林","name":"🔞森林资源","type":1,"api":"http://senlinzy2.com/api.php/provide/vod/?ac=list","searchable":1,"filterable":1},
{"key":"大地av","name":"🔞大地AV","type":0,"api":"https://dadiapi.com/apple_m3u8.php","playUrl":"https://play.dadiapi.com/watch?url=","searchable":1,"quickSearch":1,"filterable":0},
{"key":"gdlsp","name":"🔞老色胚","type":0,"api":"https://www.gdlsp.com/api/xml.php"},
{"key":"naixxzy.com","name":"🔞奶香资源","type":1,"api":"https://naixxzy.com/api.php/provide/vod/?ac=list","searchable":1,"filterable":1},
{"key":"苹果小电影","name":"🔞苹果资源","type":0,"api": "https://www.pgxdy.com/api/xml.php","searchable":1,"quickSearch":1,"filterable":1}, 
{"key":"kxgav","name":"🔞开心果AV","type":0,"api":"https://www.kxgav.com/api/xml.php"},
{"key":"lltv_iKun","name":"🔞iKun资源","type":1,"api":"https://www.ikunzy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable": 1},
{"key":"大地","name":"🔞DaDi资源","type":0,"style":{"type":"rect","ratio":1.485},"api": "http://dadiapi.com/api.php","searchable":1},
{"key":"*91麻豆","name":"🔞91麻豆","type":1,"api":"https://91md.me/api.php/provide/vod/","searchable":0,"quickSearch":0},
{"key":"♥️森林专场","name":"🔞森林资源","type":1,"api":"https://beiyong.slapibf.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1,"filterable":1},
{"key":"玉兔专场","name":"🔞玉兔资源","type":1,"api":"https://apiyutu.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1,"filterable":1},
{"key": "玉兔","name":"🔞玉兔采集","type":1,"api": "https://py.nxog.eu.org/https://apiyutu.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1,"filterable":1},
{"key":"❤淫水机资源","name":"🔞淫水资源","type":0,"playerType":2,"api":"https://www.xrbsp.com/api/xml.php","searchable":0,"quickSearch":0},
{"key":"香奶儿资源","name":"🔞香奶资源","type":0,"api":"https://www.gdlsp.com/api/xml.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"kxgav.com","name":"🔞开心资源","type":0,"api":"https://www.kxgav.com/api/xml.php","quickSearch":1,"searchable":1,"filterable":1},
{"key":"senlinzy.com","name":"🔞森林资源","type":1,"api":"https://slapibf.com/api.php/provide/vod/?ac=list","searchable":1,"filterable":1},
{"key":"乐播资源","name":"🔞乐播资源","type":1,"api":"https://lbapi9.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"喇叭","name":"🔞喇叭资源","type":0,"style":{"type":"rect","ratio":1.485},"api":"http://lbapiby.com/api.php/provide/vod/at/xml","searchable":1},
{"key": "www.caoliuzyw.com","name":"🔞草榴资源","type":1,"api":"https://www.caoliuzyw.com/api.php/provide/vod/?ac=list","playurl":"https://jx.caoliuzywcdnjx.com:188/m3u8.php?url=","searchable":1,"filterable":1},
{"key":"性南国","name":"🔞南国资源","type":1,"api":"https://api.sexnguon.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},

{"key":"csp_XBPQ_奶很大","name":"🔞奶大资源","type":3,"api":"csp_XBPQ","jar":"https://py.nxog.eu.org/https://raw.githubusercontent.com/guot55/yg/main/jar/hl.jar","searchable":1,"quickSearch":1,"filterable":0,"ext":{"请求头":"手机","站名":"奶很大","主页url":"https://7nwzz.naihenda-2f.buzz/index.php","直接播放":"1","标题":"<p&&</p>","图片":"data-src=\"&&\"","跳转播放链接":"var player_data*url\":\"&&\"","搜索模式":"1","搜索url":"/index.php/vodsearch/{wd}----------{pg}---.html","分类url":"https://7nwzz.naihenda-2f.buzz/index.php/vodtype/{cateId}-{catePg}.html","分类":"草莓猛料$136#玩偶姐姐$133#兔子先生$131#91茄子$129#奇兵有码$27#步兵无码$28#国产视频$1#日本视频$2#中文字幕$9#无码中文$34#主播大秀$12#欧美视频$5#女神学生$16#娇妻素人$18空姐模特$19#职场同事$23#强奸中文$35#制服中文$38#出轨中文$41#韩国制服主播$43#制服师生$50"}},
{"key":"糖心","name":"🔞糖心次元","type":3,"api":"csp_XBPQ","jar":"https://py.nxog.eu.org/https://raw.githubusercontent.com/guot55/yg/main/jar/hl.jar","style":{"ratio":1.7},"ext":{"数组":"<section&&</section","副标题":"添加时间:&&</span>","嗅探词":"cdn2020.com#m3u8", "分类url":"http://www.txcyeat.buzz/index.php/vodtype/{cateId}-{catePg}.html;;z","分类":"国产片商$32#节目企划$3#代理节目$2#麻豆原创$1#导演系列$5#MDS系列$6#MDX系列$7#MD系列$4#MDXS系列$8#兔子先生$10#大鸟十八$17#疯拍系列$18#KISS糖果屋$19#小鹏奇啪行$20#30天解密麻豆$22#突袭女优计划$23#女神羞羞研究所$24#小哥哥艾理$27#情趣K歌房$31#淫欲游戏王$40#麻豆不回家$41#叮叮映画$71#涩会$72#豚豚创媒$75#MDL系列$46#MMZ系列$50#MAD系列$53#MDWP系列$58#MSD系列$64#MDM恋爱咖啡$74#MDUS系列$78#MXJ系列$79#MKY系列$87#MAN系列$89#MCY系列$96#MDAG系列$100#MDHT系列$101#BLX系列$115#MPG系列$116#果冻传媒$11#皇家华人$12#吴梦梦无套系列$13#PsychoPorn色控$14#蜜桃影像传媒$15#天美传媒$45#乌鸦传媒$33#精东影业$34#SWAG$36#91制片厂$52#MSM性梦者$65#爱妃传媒$76#辣椒原创$80#O-STAR$81#肉肉传媒$91#渡边传媒$95#葵心娱乐$97#红斯灯影像$103#麻麻传媒$104#蝌蚪传媒$105#Pussy Hunter$106#桃花源$108#女优淫娃培训营$42#狼人插$54#女优擂台摔角狂热$55#恋爱巴士$61#男女优生死斗$66#情人劫密室逃脱$67#换妻$68#你好同学$69#禁欲小屋$77#鲍鱼的胜利$84#性爱自修室$88#春游记$92#心动的性号$93#情趣大富翁$94#寻宝吧女神$99#男优练习生$102#女神体育祭$110#麻豆高校$111#野外露初$112#星空无限传媒$47#乐播传媒$48#大象传媒$59#MINI传媒$62#糖心$73#葫芦影业$82#天马传媒$83#CCAV成人头条$90#性视界传媒$109#SA国际传媒$113#起点传媒$114#91茄子$117#草莓猛料$118" }},
{"key":"快活影網","name":"🔞快活影视","type":3,"api":"csp_XBPQ","jar":"https://gitee.com/lwlxh/tvhome/raw/master/o.jar","searchable":1,"quickSearch":1,"filterable":1,"ext":{"主页url":"https://www.444vva.com/yazhouxingai/index.html","播放数组":"mod play-list&&</ul","跳转播放链接":"var playUrl=\"&&\"","链接":"href=\"&&\"","标题":"alt=\"&&\"","直接播放":"1","分类url":"https://www.444vva.com/{cateId}/{class}/index.html","分类":"亚洲性爱$yazhouxingai#欧美高清$oumeixingai#亚洲无码$yazhouav#欧美短AV$oumeiav#熟女人妻$shunvrenqi#丝袜制服$siwazhifu#中文熟女$luanlunshunv#三级经典$sanjijingdian"}},
{"key":"JAVSB","name":"🔞JAVSB资源","type":3,"api":"csp_XBPQ","jar":"https://gitee.com/lwlxh/tvhome/raw/master/o.jar","ext":{"主页url":"https://jav.sb/","直接播放":"1","数组":"class=\"relative aspect-w-16 aspect-h-9 rounded overflow-hidden shadow-lg\"&&</div>","图片":"data-src=\"&&\"","标题":"alt=\"&&\"","链接":"href=\"&&\"","分类url":"https://jav.sb/javtype/{cateId}-{catePg}.html","分类":"日本有碼$Censored#日本無碼$Uncensored#FC2-PPV$FC2-PPV#無碼破解$Mosaic_Removed#中文字幕$CHN_SUB#MGS動画$MGS#寫真$Adult_IDOL#國產$Asian_Amateur#欧美$Western_Porn"}},
{"key":"手鸡助手","name":"🔞手鸡助手","type":3,"api":"csp_XBPQ","jar":"https://gitee.com/lwlxh/tvhome/raw/master/o.jar","ext":{"请求头":"手机","直接播放":"1","分类url":"https://mcpg.sjzs199p.buzz/?mod=videos&cateid={cateId}&page={catePg}","分类":"日韩有码$480#日韩无码$481#中文字幕$483#AV解说$485#欧美情色$482#国产情色$479#网红主播$484#卡通动漫$1505","播放标题":"<h1&&</h1>","搜索url":"https://mcpg.sjzs199p.buzz/?mod=videos&wd={wd}"}},
{"key":"jap影網","name":"🔞6av┃影视","type":3,"api":"csp_XBPQ","jar":"https://gitee.com/lwlxh/tvhome/raw/master/o.jar","searchable":1,"quickSearch":1,"filterable":1,"ext":{"主页url":"https://www.1av.shop/vodtype/25.html","播放数组":"mod play-list&&</ul","跳转播放链接":"var player_aaaa*url\":\"&&\"","链接":"href=\"&&\"","标题":"alt=\"&&\"","直接播放":"1","分类url":"https://www.1av.shop/vodtype/{cateId}-{catePg}.html;;z","分类":"国产视频$1#欧美高清$18#日韩视频$17#熟女人妻$25#国产传媒$11#精品推荐$16#网曝私密$2#三级电影$21"}},
{"key":"11影網","name":"🔞112vv影视","type":3,"api":"csp_XBPQ","jar":"https://gitee.com/lwlxh/tvhome/raw/master/o.jar","searchable":1,"quickSearch":1,"filterable":1,"ext":{"主页url":"https://www.112vv.me/vodtype/26.html","播放数组":"mod play-list&&</ul","跳转播放链接":"var player_aaaa*url\":\"&&\"","链接":"href=\"&&\"","标题":"alt=\"&&\"","直接播放":"1","分类url":"https://www.112vv.me/vodtype/{cateId}-{catePg}.html;;z","分类":"国产视频$6#欧美高清$24#日韩视频$23#熟女人妻$32#国产传媒$12#亚洲专区$22#中文字幕$25#三级电影$26#高清名优$38#日本素人$37#少女萝莉$31#强奸乱伦$29#制服丝袜$30#童颜巨乳$28"}},
{"key":"传媒二区","name":"🔞传媒二区","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":{"主页url":"https://www.34gaobk.com/index.html","数组":"<div class=\"card mb-0\">&&</a","标题":"atl=\"&&\"","副标题":"img-tag\">&&</div>","简介":"document.title='&&'","直接播放":"1","搜索模式":"1","搜索url":"https://www.34gaobk.com/gaosearch/{wd}-/page/{pg}/","分类数组":"<a&&/a>","分类标题":">&&<","分类ID":"/gaotype/&&.html","分类url":"https://www.34gaobk.com/gaotype/{cateId}_{catePg}.html[https://www.34gaobk.com/gaotype/{cateId}.html]"},"jar":"https://ghfast.top/https://raw.githubusercontent.com/guot55/yg/main/jar/hl.jar"},
{"key":"麻豆","name":"🏆麻豆资源","type":3,"changeable":1,"searchable":1,"quickSearch":1,"filterable":1,"api":"csp_XBPQ","jar":"https://ghfast.top/https://raw.githubusercontent.com/guot55/yg/main/jar/xyqxbpq.jar","style":{"ratio":1.7},"ext":{"搜索url":"http://gcmd.cc/index.php/vod/search/page/{pg}/wd/{wd}.html", "分类": "日本视频$1#麻豆视频$2", "分类url": "http://gcmd.cc/index.php/vod/show/class/{class}/id/{cateId}/page/{catePg}.html", "直接播放": "1" }}
],
    //解析
"parses":[
{"name":"云解析","type":0,"url":"https://yparse.ik9.cc/index.php?url="},
{"name":"虾米","type":0,"url":"https://jx.xmflv.com/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
{"name":"咸鱼","type": 0,"url":"https://jx.xymp4.cc/?url="},
{"name":"剖云","type":0,"url":"https://www.pouyun.com/?url="},
{"name":"邦 宁","type":0,"url":"https://video.isyour.love/player/getplayer?url="},
{"name":"麒麟","type":0,"url":"https://www.cgdyw.net/jiexi/jiexi-gf/?url="},
{"name":"二次萌","type":0,"url":"https://www.ecmys.com/player/art.php?url="},
{"name":"味精","type":0,"url":"http://154.44.26.196/player/qu.php?v="},
{"name":"player","type": 0,"url":"https://jx.playerjy.com/?url="},
{"name":"夜幕","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}},
{"name":"全能","type":1,"url":"https://zy.qiaoji8.com/neibu.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","tnmb","seven","bilibili","1905"],"header":{"User-Agent":"okhttp/4.9.1"}}},
{"name":"全能.","type":1,"url":"https://zy.qiaoji8.com/gouzi.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","tnmb","seven","bilibili","1905","NetFilx"],"header":{"User-Agent":"okhttp/4.9.1"}}},
{"name":"冰豆","type":0,"url":"https://bd.jx.cn/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
{"name":"M3U8","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="},
{"name":"超快","type":0,"url":"https://www.ckplayer.vip/jiexi/?url=","ext":{"flag":["qq","qiyi","优酷","mgtv"]}},
{"name":"盘古","type":0,"url":"https://www.pangujiexi.com/jiexi/?url="},
{"name":"PM","url":"https://www.playm3u8.cn/jiexi.php?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}}
 ]}

